[package]
name = "test_front"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
log = "0.4.27"
web-sys = "0.3.77"
frontend_commons = {path="../frontend_commons"}
test_back = {path="../test_back"}
wasm-bindgen = "0.2.108"
image = "0.25.9"
