[build]
offline = true
public_url = "/test/static"

[watch]
watch = ["../frontend_commons", "."]
ignore = ["js/"]

[[hooks]]
stage = "pre_build"
command = "esbuild"
command_arguments = ["main.ts", "--bundle", "--outdir=js", "--tsconfig=./tsconfig.json"]
