[package]
name = "test_back"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0.219", features = ["derive"]}
backend_commons = {path = "../backend_commons"}
log = "0.4.27"
tracing = "0.1.41"
postcard = { version = "1.1.3", features = ["use-std"] }