[package]
name = "frontend_commons"
version = "0.1.0"
edition = "2024"

[dependencies]
backend_commons = { path = "../backend_commons" }
serde = "1.0.219"
serde_cbor = "0.11.2"
wasm-bindgen = "0.2.108"
web-sys = "0.3.77"
